import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
  ]),

  {
    // src/components/ui is generated by `npx shadcn add` and re-generated
    // whenever a component is updated, so hand-edits there do not survive.
    // The React Compiler flags shadcn's carousel for syncing the embla API
    // through an effect - a pattern in upstream's code, not ours. Everything
    // else stays enabled, and this exemption does not apply to any file we
    // author.
    files: ['src/components/ui/**/*.tsx'],
    rules: {
      'react-hooks/set-state-in-effect': 'off',
    },
  },
]);

export default eslintConfig;
