import type { Metadata, Viewport } from 'next';
import { Inter, JetBrains_Mono, Plus_Jakarta_Sans } from 'next/font/google';

import { Providers } from '@/components/providers/providers';

import './globals.css';

/* Part H1 type stack. `display: swap` keeps CLS under the J1 budget of 0.05. */
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta',
  display: 'swap',
  weight: ['500', '600', '700', '800'],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains-mono',
  display: 'swap',
  weight: ['400', '500', '600'],
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000';

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'Bazaar - Everything you need, delivered across Nepal',
    template: '%s | Bazaar',
  },
  description:
    'Shop electronics, fashion and home essentials with fast delivery across all 77 districts. Pay with eSewa, Khalti, card or cash on delivery.',
  applicationName: 'Bazaar',
  keywords: ['ecommerce', 'Nepal', 'online shopping', 'eSewa', 'Khalti', 'delivery'],
  openGraph: {
    type: 'website',
    siteName: 'Bazaar',
    locale: 'en_NP',
    url: siteUrl,
  },
  twitter: { card: 'summary_large_image' },
  // J2: cart, checkout and admin stay out of the index.
  robots: { index: true, follow: true },
  // The manifest route is generated by app/manifest.ts; naming it here is what
  // puts the <link rel="manifest"> in the document head.
  manifest: '/manifest.webmanifest',
  icons: {
    icon: [
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/icons/apple-touch-icon.png',
  },
  appleWebApp: {
    capable: true,
    title: 'Bazaar',
    // The dark surface, so the iOS status bar blends into the app shell.
    statusBarStyle: 'black-translucent',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // The installed app runs edge to edge; without this the safe-area insets are
  // never exposed and the notch overlaps the navbar.
  viewportFit: 'cover',
  // Matches --bz-bg in both themes so the mobile browser chrome blends in.
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#FAFBFC' },
    { media: '(prefers-color-scheme: dark)', color: '#0B0E1A' },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    // suppressHydrationWarning is required: next-themes writes the theme class
    // on <html> before React hydrates.
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${plusJakarta.variable} ${jetbrainsMono.variable}`}
      >
        {/* The first thing in the tab order, and invisible until it has focus.
            Without it a keyboard user re-traverses the navbar, the mega menu
            and the search field on every single page before reaching the
            content (WCAG 2.4.1). Every shell gives its <main> this id. */}
        <a
          href="#main"
          className="sr-only z-100 rounded-md bg-primary-solid px-4 py-2 text-sm font-medium text-primary-foreground focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:ring-2 focus:ring-ring focus:outline-none"
        >
          Skip to content
        </a>

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
